### ISSUE TITLE
3d view not persistent using permalink

### ISSUE THREAD

**Issue by Rdataflow** [geoadmin/web-mapviewer#866] opened 2024-05-27 11:57 UTC
**repro steps**
1. open https://test.map.geo.admin.ch/#/map?lang=en&sr=3857&center=863226.99,5903099.04&camera=7.7545,46.760686,4236,-10,198,&z=15.355&3d&bgLayer=ch.swisstopo.swisstlm3d-karte-farbe_3d&topic=ech&swisssearch=Altitudinal+zones+1975&layers=ch.bafu.landesforstinventar-vegetationshoehenmodell_relief;ch.bafu.wald-vegetationshoehenstufen_1975
or open https://s.geo.admin.ch/e584e3iiyed5

**expected**
reproduce the same view  (notice Niesen seen from North)
![image](https://github.com/geoadmin/web-mapviewer/assets/26090254/086fd125-d359-41e3-99e7-3baab6319931)

**actual**
- completely different view
![image](https://github.com/geoadmin/web-mapviewer/assets/26090254/c151cc4c-62a3-4a11-88bb-28d9984de9eb)

- nit: search dialog is open and focused unexpectedly

**Comment by Rdataflow** [comment] 2024-05-28 06:54
@pakb also consider the `Preview` is out of sync unexpectedly

![image](https://github.com/geoadmin/web-mapviewer/assets/26090254/24443bfd-5714-4bb3-9f4f-a5a5a4882bf6)

**Comment by pakb** [comment] 2024-05-28 07:39
I think the issue is related, from what I see the camera is not properly handled while reloading, and a preview does a bit the same thing as reloading...

**Comment by pakb** [comment] 2024-06-12 07:33
Should have been fixed on https://test.map.geo.admin.ch/
please test again and give us some feedback if something is still wrong :+1:

**Comment by Rdataflow** [comment] 2024-06-12 15:49
On iphone opening the shortlink now opens a void map with no content. Only after reloag?ding the content appears....

**Comment by Rdataflow** [comment] 2024-08-12 14:45
@ltshb confirm this issue is fixed now

**Closed** 2024-08-12 14:45 UTC
